/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package evaluacionFinal;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;



/**
 * Ventana de reproducción de audio.
 * @author Alvaro Maximino Linares Herrera
 */
public class VentanaInternaReproductor extends javax.swing.JInternalFrame {
    SMPlayer player;
    /**
     * Constructor
     * @param f File, archivo que vamos a reproducir.
     */
    public VentanaInternaReproductor(File f) {
        initComponents();
        this.setSize(420, 90);
        player = new SMClipPlayer(f);
        LineListener lineListener = new LineListener(){
            @Override
            public void update(LineEvent event) {
                if(event.getType()==LineEvent.Type.START) {
                    player.play();
                    
                }
                if(event.getType()==LineEvent.Type.STOP) {
                    player.stop();
                }
            }
        };
        ((SMClipPlayer)player).setLineListener(lineListener);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPlay = new javax.swing.ButtonGroup();
        stopToggleButton = new javax.swing.JToggleButton();
        playToggleButton = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(400, 90));

        grupoPlay.add(stopToggleButton);
        stopToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica11/iconos/StopDisabled_48x48.png"))); // NOI18N
        stopToggleButton.setDisabledIcon(null);
        stopToggleButton.setPreferredSize(new java.awt.Dimension(200, 90));
        stopToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopToggleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopToggleButton, java.awt.BorderLayout.LINE_END);

        grupoPlay.add(playToggleButton);
        playToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosPractica11/iconos/PlayPressed_48x48.png"))); // NOI18N
        playToggleButton.setSelected(true);
        playToggleButton.setPreferredSize(new java.awt.Dimension(200, 90));
        playToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playToggleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playToggleButton, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playToggleButtonActionPerformed
        ((SMClipPlayer)player).setLineListener(null);
        if(player!=null) player.play();
        playToggleButton.setIcon(new javax.swing.ImageIcon("src/iconosPractica11/iconos/PlayPressed_48x48.png"));//Ruta
        stopToggleButton.setIcon(new javax.swing.ImageIcon("src/iconosPractica11/iconos/StopDisabled_48x48.png"));
    }//GEN-LAST:event_playToggleButtonActionPerformed

    private void stopToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopToggleButtonActionPerformed
        ((SMClipPlayer)player).setLineListener(null);
        if(player!=null) player.stop();
        playToggleButton.setIcon(new javax.swing.ImageIcon("src/iconosPractica11/iconos/PlayDisabled_48x48.png"));//Ruta
        stopToggleButton.setIcon(new javax.swing.ImageIcon("src/iconosPractica11/iconos/StopNormalRed_48x48.png"));
    }//GEN-LAST:event_stopToggleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoPlay;
    private javax.swing.JToggleButton playToggleButton;
    private javax.swing.JToggleButton stopToggleButton;
    // End of variables declaration//GEN-END:variables
}
