/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package evaluacionFinal;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.List;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.media.Buffer;
import javax.media.CannotRealizeException;
import javax.media.CaptureDeviceInfo;
import javax.media.CaptureDeviceManager;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.format.YUVFormat;
import javax.media.util.BufferToImage;

/**
 * Ventana de visualización de cámara.
 * @author Alvaro Maximino Linares Herrera
 */
public class VentanaInternaCamara extends javax.swing.JInternalFrame {

    private Player p;
    /**
     * Constructor de VentanaInternaCamara.
     */
    private VentanaInternaCamara() {
        initComponents(); 
        
        try{       
            CaptureDeviceInfo deviceInfo; 
            List<CaptureDeviceInfo> deviceList = CaptureDeviceManager.getDeviceList(new YUVFormat()); 
            deviceInfo = deviceList.get(0); 
            this.setLayout(new BorderLayout());
            this.setSize(350,280); 
            MediaLocator ml = deviceInfo.getLocator(); 
            //MediaLocator ml = new MediaLocator("vfw://0");
            p = Manager.createRealizedPlayer(ml); 
            Component areaVisual = p.getVisualComponent(); 
            if(areaVisual!=null) this.add(areaVisual); 
            Component panelControl = p.getControlPanelComponent(); 
            if(panelControl!=null) this.add(panelControl); 
            p.start(); 
        } catch(IOException | CannotRealizeException | NoPlayerException e) {
        System.err.println("Error de acceso a camara");
        } 

    }
    /**
     * Este método llama al constructor de la clase y nos devuelve la VentanaInternaCamara creada.
     * @return VentanaInternaCamara.
     */
    public VentanaInternaCamara getInstance(){
        VentanaInternaCamara v = new VentanaInternaCamara();
        return v;
    }
    /**
     * Este método sirve para obtener una captura de lo que estemos visualizando desde la cámara.
     * @param player objeto Player.
     * @return BufferedImage obtenida de la cámara.
     */
    public BufferedImage getFrame(Player player){ 
        FrameGrabbingControl fgc;
        String claseCtr = "javax.media.control.FrameGrabbingControl";
        fgc = (FrameGrabbingControl)player.getControl(claseCtr);
        Buffer bufferFrame = fgc.grabFrame();
        BufferToImage bti;
        bti=new BufferToImage((VideoFormat)bufferFrame.getFormat());
        Image img = bti.createImage(bufferFrame);
        return (BufferedImage)img;
    }
    /**
     * Sirve para obtener el Player de la clase.
     * @return objeto tipo Player.
     */
    public Player getPlayer(){
        return p;
    }
    /**
     * Método para iniciar la visualización de la cámara.
     */
    public void play(){
        p.start();
    }
    /**
     * Método para parar la visualización de la cámara.
     */
    public void close(){
        p.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
